name: projeto_integrador2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  image_picker: ^1.2.0
  google_fonts: ^6.3.1
  google_sign_in: ^6.2.1
  flutter_svg: ^2.2.1
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.3
  http: ^1.2.1
  mockito: ^5.6.1
  dev: ^1.0.0
  build_runner: ^2.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: any
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:

  uses-material-design: true
  assets:
      - assets/images/google_logo.svg
